name: Publish to NPM

on:
  push:
    paths:
      - 'biome.jsonc'
      - '.github/workflows/publish.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Prepare git and update version
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pnpm lint:fix
          pnpm run auto-version
          git commit -m "tags: updated tags" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Publish to NPM
        run: pnpm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
